package com.shao.house.house.mapper;

import com.shao.house.house.model.HouseUser;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface HouseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated
     */
    int insert(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated
     */
    int insertSelective(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated
     */
    HouseUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HouseUser record);

    //根据房屋ID找到 houseUser
    List<HouseUser> getMaster(Long id);
    //根据用户id找到 houseUser
    List<HouseUser> getMyHoust(long id);
}