package com.shao.house.house.model;

import java.util.Date;

public class HouseUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_user.house_id
     *
     * @mbggenerated
     */
    private Long houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_user.type
     *
     * @mbggenerated
     */
    private Boolean type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_user.id
     *
     * @return the value of house_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_user.id
     *
     * @param id the value for house_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_user.house_id
     *
     * @return the value of house_user.house_id
     *
     * @mbggenerated
     */
    public Long getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_user.house_id
     *
     * @param houseId the value for house_user.house_id
     *
     * @mbggenerated
     */
    public void setHouseId(Long houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_user.user_id
     *
     * @return the value of house_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_user.user_id
     *
     * @param userId the value for house_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_user.create_time
     *
     * @return the value of house_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_user.create_time
     *
     * @param createTime the value for house_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_user.type
     *
     * @return the value of house_user.type
     *
     * @mbggenerated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_user.type
     *
     * @param type the value for house_user.type
     *
     * @mbggenerated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "HouseUser{" +
                "id=" + id +
                ", houseId=" + houseId +
                ", userId=" + userId +
                ", createTime=" + createTime +
                ", type=" + type +
                '}';
    }
}